language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - hhvm
  - nightly

env:
  - WP_VERSION=latest WP_MULTISITE=0

before_script:
  - composer self-update
  - composer install
#  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

#script: vendor/bin/phpunit